### PR TITLE
Dark Theme Support

### PR DESCRIPTION
**Pull request by Quadriyanney**
1. Added Dark Theme Support
2. Removed unused code/files

### CODE REVIEW

**Comment by Quadriyanney** [comment]
@emmanuelkehinde

**Comment by Quadriyanney** [comment]
Uploading Screen_Recording_20210613-193257_TwittaSave.mp4…

**Comment by Quadriyanney** [comment]
https://user-images.githubusercontent.com/13119278/121818422-f32ecf00-cc3b-11eb-8920-ecf4385f7e7d.mp4

**Comment by emmanuelkehinde** [comment]
Thank you @Quadriyanney

**Pull request merged**
